version: '3.8'

services:
  dttp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dttp-ai-server
    restart: unless-stopped
    ports:
      - "8000:5000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=https://dttp-project.vercel.app,http://localhost:3000
      # Database configuration (you'll need to update these)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      # Model configuration
      - MODELS_CACHE_DIR=/app/model_cache
      - EMBEDDINGS_CACHE_DIR=/app/embeddings_cache
      - MAX_WORKERS=4
      - ENABLE_MODEL_PARALLELISM=true
    volumes:
      # Persist model and embeddings cache
      - model_cache:/app/model_cache
      - embeddings_cache:/app/embeddings_cache
      - logs:/app/logs
    networks:
      - dttp-network
    # Optional: Memory limits for large ML models
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  # Optional: Add a reverse proxy (recommended for production)
  # nginx:
  #   image: nginx:alpine
  #   container_name: dttp-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - dttp-backend
  #   networks:
  #     - dttp-network

volumes:
  model_cache:
    driver: local
  embeddings_cache:
    driver: local
  logs:
    driver: local

networks:
  dttp-network:
    driver: bridge
