version: "3.8"

services:
  dttp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dttp-ai-server-dfn5b
    restart: unless-stopped
    ports:
      - "8000:5000"
    env_file:
      - .env.dfn5b
    volumes:
      # Persist model and embeddings cache
      - model_cache:/app/model_cache
      - embeddings_cache:/app/embeddings_cache
      - logs:/app/logs
      # Add sample images
      - ./images:/app/images
    networks:
      - dttp-network
    # Reduced memory for single model
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  model_cache:
    driver: local
  embeddings_cache:
    driver: local
  logs:
    driver: local

networks:
  dttp-network:
    driver: bridge
