version: '3.8'

services:
  dttp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dttp-ai-server-multimodel
    restart: unless-stopped
    ports:
      - "8000:5000"
    env_file:
      - .env.multimodel
    volumes:
      # Persist model and embeddings cache
      - model_cache:/app/model_cache
      - embeddings_cache:/app/embeddings_cache
      - logs:/app/logs
    networks:
      - dttp-network
    # Increased memory limits for multiple models
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 6G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s  # Longer startup time for multiple models

volumes:
  model_cache:
    driver: local
  embeddings_cache:
    driver: local
  logs:
    driver: local

networks:
  dttp-network:
    driver: bridge
