version: "3.8"

services:
  dttp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dttp-ai-server-minimal
    restart: "no" # Don't restart on failure to avoid crash loops
    ports:
      - "8000:5000"
    env_file:
      - .env.minimal-working
    volumes:
      - model_cache:/app/model_cache
      - embeddings_cache:/app/embeddings_cache
      - logs:/app/logs
    networks:
      - dttp-network
    # Reduced memory for CLIP only
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  model_cache:
    driver: local
  embeddings_cache:
    driver: local
  logs:
    driver: local

networks:
  dttp-network:
    driver: bridge
